name: warehouse
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.2+1
  shared_preferences:
  get_version: ^0.2.2
  url_launcher:
  splashscreen:
  progress_dialog:
  intl:
  datetime_picker_formfield:
  horizontal_data_table:
  dio:
  geolocator: ^5.3.2
  location:
  google_maps_flutter: ^1.0.1
  rxdart:
  toast:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/warelogos.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/pharmacist.png
    - assets/images/storecard.png
    - assets/images/registration.jpg
    - assets/images/nextleft.png
    - assets/images/location.png
    - assets/images/carddurg.png
    - assets/images/pharmacard.png
    - assets/images/mappharma.png
    - assets/images/pharname.png
    - assets/images/phone.png
    - assets/images/slider.jpg
    - assets/images/durgcardhome.png
    - assets/images/compaincardhome.png
    - assets/images/morehome.png
    - assets/images/homeicon.png
    - assets/images/drughome.png
    - assets/images/mydrug.png
    - assets/images/myreqhome.png
    - assets/images/offerhome.png
    - assets/images/settinghome.png
    - assets/images/timer.png
    - assets/images/compainhome.png
    - assets/images/homes.png
    - assets/images/warelogos.png

    - assets/images/mores.png
    - assets/images/discount.jpg
    - assets/images/gift.jpg
    - assets/images/offerde.png
    - assets/images/buy.png
    - assets/images/offerw.png
    - assets/images/offerws.png
    - assets/images/warelogo.png
    - assets/images/request.png
    - assets/images/requests.png

    - assets/images/pharmacists.png
    - assets/images/store.png
    - assets/images/stores.png
    - assets/images/offerd.png
    - assets/images/defaulc.jpg
    - assets/images/emaillogo.png
    - assets/images/pharmap.png
    - assets/images/liclogo.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
